FROM alpine-jdk:base
MAINTAINER javaonfly
COPY files/employee-config-server.jar /opt/lib/
RUN mkdir /var/lib/config-repo
COPY config-repo /var/lib/config-repo
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/employee-config-server.jar"]
VOLUME /var/lib/config-repo
EXPOSE 9090